# Generated by Django 5.0.1 on 2024-01-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Header')),
                ('body', models.TextField(max_length=3000, verbose_name='Body of the post')),
                ('author', models.CharField(max_length=100, verbose_name='I am the author of this book')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Data')),
            ],
        ),
    ]
