# Generated by Django 5.0.1 on 2024-02-01 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0002_rename_body_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='body',
        ),
    ]
