# Generated by Django 5.0.1 on 2024-02-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0012_auto_20240212_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags_old',
        ),
        migrations.DeleteModel(
            name='PostTag',
        ),
    ]
